<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6bcdx1q\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6bcdx1q/appProdProjectContainer.php') {
    touch(__DIR__.'/Container6bcdx1q.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container6bcdx1q\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container6bcdx1q\appProdProjectContainer([
    'container.build_hash' => '6bcdx1q',
    'container.build_id' => 'ded9f19c',
    'container.build_time' => 1595662820,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6bcdx1q');
